### ISSUE TITLE
Add our team demonym (teamonym?)

### ISSUE THREAD

**Issue by add1sun** [LullabotEducation/emphandbook#12]
When we were part of Lullabot (Education) we were "bots".  Now that we have a new name, we need a new um, naming thing. (Demonym is the name for where you are from, so I've no idea what a company name is.)

One suggestion we kicked around at our retreat is osito/osita (also typed osit@ or ositx to be gender neutral). That means little bear or teddy bear in Spanish. (And we all know bears like honey, like the hive logo we have, right?)

The tricky bit with this is that it is gendered by default. We can use the gender neutral spellings for text, but they aren't easy to say that way. We could come up with another ending that suits our purposes though if this is the name we want to run with. Some ideas could be something like ositi or ositiari. Or we could adopt the non-gendered spelling into the word: ositat or ositex.

Any thoughts, please do share.

**Comment by eojthebrave** [comment]
What's the use case for this? When we're talking to each other? When we're talking to the public? Personally I prefer things like "team", "co-workers", and other demonyms that are more commonly used. I always found `bots to be a bit cliquish and exclusionary. Especially when used in public.

**Comment by blakehall** [comment]
I really like the osito/osita concept, but the gendered nature of it is a bit tricky.

Conceptually I like the idea that we could use a bear of some sort as a mascot across our various products, or with swag. Kind of like how npm uses their wombat.
