### ISSUE TITLE
Update Do Great Work value

### ISSUE THREAD

**Issue by add1sun** [LullabotEducation/emphandbook#17]
At the Sedona retreat we noted that Do Great Work can also encompass "do good". The effects of doing good aren’t captured in our current description.

**Comment by add1sun** [comment]
I'm struggling with how to word this one, and I'm not sure if I'm capturing what was intended here. I also wanted to replace the word craftmanship while we're here, to remove the gendered term. I'd like to massage this in this issue before trying to propose a final change in a PR.

Any feedback on:

> Do great work
> We value skillful and impactful work, and set high standards for ourselves. We encourage each other to strive for those standards, helping each person grow, and make sure that we deliver not only a quality product but also have a positive impact on the world.

@eojthebrave @blakehall @agentolivia @philippa5 @ashleyrian

**Comment by eojthebrave** [comment]
I think this captures both the desire to pour ourselves into the quality of the work. As well as that we want to make the world a better place. But agree that it just kind of feels a little flat.

I dug up the notes from this conversation here https://paper.dropbox.com/doc/2019-Palm-Springs-Retreat-Notes--A4xT7v2lo8noVEA1esgOQzSIAg-WfXK7ylyABoAoLssfFwub and here https://docs.google.com/document/d/1TSYnzj3kLgZW_8uLh_7pwyRsene1B_-hq5aBRLmxMyI/edit#heading=h.4wcq4gkrgtkm but there's no a whole lot related to this particular value. And I'm finding it difficult to recall the conversation at this point.

I would be okay with this as is. And if we're still not feeling it maybe make it a point of conversation at the next retreat and plan to update it while the memory is fresh.

**Comment by philippa5** [comment]
Okay....was trying to massage this to reflect the larger idea- of doing good in the world as well as at work... What about something like this? 

**Do great work**
We set high standards for ourselves, valuing skillful and impactful work. We encourage each other to strive for those standards and help each other to grow at their jobs and in their lives. We make sure we deliver not only a top quality product, but the space and support to have a positive and serendipitous impact on the world.

**Comment by blakehall** [comment]
@add1sun I think the version you proposed works for me. It's straight forward without sounding trite or overly corporate jargony.
