### ISSUE TITLE
Change sabbatical eligibility to 7 years

### ISSUE THREAD

**Issue by add1sun** [LullabotEducation/emphandbook#23]
My sabbatical time was really, really good, and I feel like everyone should have an opportunity to do that sooner rather than later. The whole thing also went very smoothly for the business as well and I think we're in a good place as a company to handle these. I think we should lower the eligibility period from 10 years to 7 years.

If we were to lower it to 7 years Joe and Blake would be immediately eligible and Amber will be eligible in October this year. (Since these 3 weren't expecting to be eligible so soon and may not have planned for that, we can extend the timeframe they have to take it beyond the normal "1 year from eligibility" to be through the end of 2021, so they have time to plan and prepare with their families.)

The next rounds after this year's eligibility would be:

- Addi, May 2022
- Joe, August 2024
- Blake, March 2025
- Ashley and Philippa, June 2025
- Jon, February 2027
- Amber, October 2027
- Addi starts the cycle again in 2029

So we'd have a little stutter step in the next few years as Joe, Blake, and I catch up to the right schedule since we're overdue on our first ones. (Technically I'd be eligible again in 2021, but that's just silly and too many people in the same year, so I figured I can push mine out 1 year off from the official date to make it space out better.)

I'm assuming folks won't object to this change generally, but does the way we handle the scheduling make sense to everyone? Are there other things we need to consider with this change?

**Comment by eojthebrave** [comment]
I don't have any objections. And your proposed schedule seems to be the least disruptive way to handle the fact that this would sort of create a backlog initially.

**Comment by agentolivia** [comment]
Sounds good to me!
