### ISSUE TITLE
Add Coaching budget to benefits

### ISSUE THREAD

**Issue by add1sun** [LullabotEducation/emphandbook#33]
I feel like life/career coaching can be very useful to everyone on the team. I've benefited from it a lot. I'm proposing to add a new company benefit that will pay for up to $2400 in coaching fees per year for each full-time employee. (I'll work on a PR shortly.)

In order to receive the benefit you need to use the services of a certified coach. You can find whoever you like and pay for the service with the company card. When submitting the expense, use Personal Education and make sure you write "coaching" in the description.

**Comment by agentolivia** [comment]
I welcome this suggestion! +1
