### ISSUE TITLE
Add work week length to handbook

### ISSUE THREAD

**Issue by add1sun** [LullabotEducation/emphandbook#34]
We don't currently define the expected work week in our handbook. We've decided to move to a 4-day/32-hour work week and we should clearly define that expectation somewhere. The specifics of it are clear, but I'm not sure the best place to add it since we don't already have a place for it. Is it considered a "benefit" (could maybe be added to the pay page?) or would it be better to address in the "welcome" section that outlines the basics of working with us?

**Comment by blakehall** [comment]
Personally, I think adding it to the last paragraph of the "Getting Used to the Distributed Work Style" section makes sense. It looks like it's the introduction to our flexible schedules, and the way we do things. Including it there feels more natural to me than in the benefits section (although it's definitely a benefit, so I can see that side too).

**Comment by agentolivia** [comment]
I think it should be listed under Benefits and added to Getting Used to the Distributed Work Style (the last paragraph, as Blake mentioned), clarifying how the 4-day work week and taking time for personal appointments, etc. co-exist.
